version: 2.1

orbs:
  greenzie: greenzie/build_and_publish_debs@0.2.0

parameters:
  manual_deploy:
    description: "Trigger a manual deploy to greenzie-public-experimental."
    type: boolean
    default: false

workflows:
  version: 2
  pushbuild:
    when:
      not: << pipeline.parameters.manual_deploy >>
    jobs:
      - greenzie/debian_build_simple:
          name: "amd64_build"
          context: GREENZIE
          generate_changelog: true

  manualdeploy:
    when: << pipeline.parameters.manual_deploy >>
    jobs:
      - greenzie/debian_build_simple:
          name: "amd64_build"
          context: GREENZIE
          generate_changelog: true
      - greenzie/debian_deploy_experimental_ssh:
          name: "deploy_to_public_experimental"
          context: GREENZIE
          repo_name: experimental-greenzie-public-focal-main
          channel: greenzie-public-experimental
          requires:
            - amd64_build
